docs(button-login): apply inline playground
nl-design-system/lux pull request #111
Opened 2024-06-05 12:22 UTC by remypar5

2024-06-06 08:14 UTC, MrSkippy approved these changes

2024-06-06 08:15 UTC, AlineNap requested changes
Lekker bezig.

2024-06-06 08:16 UTC, remypar5 commented on packages/storybook/src/web-components/button-login/button-login.mdx
> +| \`--lux-button-login-font-line-height\` | \`24px\`                 |
Goed gespot! Ik heb dit uit jouw documentatievoorbeeld overgenomen, dus dat moet daar ook gecorrigeerd worden

2024-06-12 09:32 UTC, AlineNap submitted a review, later dismissed

2024-06-12 09:32 UTC, AlineNap commented on packages/storybook/src/web-components/button-login/button-login.mdx
> +| \`--lux-button-login-line-height\` | \`24px\`                 |
```suggestion
| \`--lux-button-login-line-height\` | \`28px\`                 |
```

2024-06-12 09:39 UTC, merged