feat(releases): NPM release van JSON tokens beschikbaar maken [Lux-247]
nl-design-system/lux pull request #118
Opened 2024-06-19 12:06 UTC by MrSkippy

Creates a package with JSON-tokens (and CSS from `dist/`)
Added Readme to the package

2024-06-20 08:23 UTC, MrSkippy commented on lerna.json
> +      "allowBranch": ["main", "LUX-247_(NPM)-Release-van-JSON-tokens-beschikbaar-maken"],
TODO for @MrSkippy : remove the feature branch again

2024-06-20 10:55 UTC, MrSkippy commented on proprietary/design-tokens/README.md
> +Meer informatie over de LUX design tokens en de lagen vind je op de pagina [Lagen van Design Tokens](https://nl-design-system.github.io/lux/?path=TODO:include-link) van onze Storybook.
TODO @MrSkippy : include correct link

2024-06-20 12:16 UTC, MrSkippy commented on .github/workflows/continuous-deployment.yml
> +    if: github.ref == 'refs/heads/main' || 'refs/heads/LUX-247_(NPM)-Release-van-JSON-tokens-beschikbaar-maken'
TODO @MrSkippy : remove branch

2024-06-24 08:13 UTC, remypar5 requested changes

2024-06-24 08:13 UTC, remypar5 commented on proprietary/design-tokens/README.md
> +In design tokens worden de keuzes opgeslagen voor het design system. De design tokens in deze package zijn de enige bron van waarheid voor de look en feel van de componenten.
```suggestion
In design tokens worden de design beslissingen vastgelegd voor het design system. De design tokens in deze package zijn de enige bron van waarheid voor de look en feel van de componenten.
```

2024-06-24 08:13 UTC, remypar5 commented on proprietary/design-tokens/README.md
> +## JSON
```suggestion
## PNPM

`pnpm add -D @lux-design-system/design-tokens`

## JSON
```

2024-07-10 14:47 UTC, remypar5 approved these changes

2024-07-10 14:54 UTC, merged