docs(design-tokens): update typography
nl-design-system/lux pull request #186
Opened 2024-08-06 09:52 UTC by remypar5

2024-08-06 16:14 UTC, AlineNap reviewed
De font-family core tokens mogen er nog bij, ze heten nu:
`ro.font-family.primary`
`ro.font-family.secondary`

Met Rijkshuisstijl project is de prefix rhs gekozen. Goed om dat over te gaan nemen ook.

2024-08-07 10:01 UTC, AlineNap requested changes
alias op de common-laag klopt nog  niet.

2024-08-07 10:01 UTC, AlineNap commented on packages/storybook/src/design-tokens/common/font-tokens.mdx
> +      <DesignTokenFontPreview token="lux.font-family.primary" reference="ro.font-family.sans" set="product" />
```suggestion
      <DesignTokenFontPreview token="lux.font-family.primary" reference="ro.font-family.primary" set="product" />
```

2024-08-07 10:48 UTC, remypar5 commented on packages/storybook/src/design-tokens/common/font-tokens.mdx
> +      <DesignTokenFontPreview token="lux.font-family.primary" reference="ro.font-family.sans" set="product" />
Done

2024-08-07 11:32 UTC, AlineNap approved these changes

2024-08-07 11:32 UTC, merged