lux en utrecht heading tokens toegevoegd.
nl-design-system/lux pull request #198
Opened 2024-08-21 09:32 UTC by AlineNap

- lux-heading tokens toegevoegd
- nl/utrecht-heading tokens toegevoegd
- lux-paragarph tokens

-----
Zie vragen in [Slack](https://logius-ux.slack.com/archives/C0739P14S1K/p1724228012379849)

2024-08-21 10:26 UTC, MrSkippy commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
> +        "value": "{lux.heading-1.line-height",
@AlineNap hier mist een `}`

2024-08-21 10:28 UTC, AlineNap commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
> +        "value": "{lux.heading-1.line-height",
```suggestion
        "value": "{lux.heading-1.line-height"},
```

2024-08-21 10:49 UTC, MrSkippy commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
Dit bestand is niet goed afgesloten, misschien even opnieuw exporteren?

2024-08-21 12:49 UTC, AlineNap commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
Ik weet niet wat je hier bedoeld. Maar zie wel dat ik hele token sets kwijt ben. utrecht-document, Utrecht-heading

2024-08-21 12:49 UTC, AlineNap commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
nu is zelfs de hele branch pleite...

2024-08-21 12:49 UTC, AlineNap commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
Kunnen we dit nog ergens terughalen? Of moet ik opnieuw beginnen?

2024-08-21 13:54 UTC, remypar5 commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
@MrSkippy wellicht kun jij dit fixen in je IDE

2024-08-21 13:57 UTC, remypar5 commented on proprietary/design-tokens/src/imported/component/heading.json
Voor deze PR ook een changeset aanmaken

2024-08-21 13:59 UTC, remypar5 requested changes

2024-08-21 13:59 UTC, remypar5 commented on proprietary/design-tokens/src/imported/nl/utrecht-heading.json
utrecht-document, paragraph, heading en $metadata hebben er ook last van

2024-08-22 12:54 UTC, closed without merging

2024-08-22 12:56 UTC, MrSkippy commented
Vanwege build-problemen en gebroken import in TS, is deze PR gesloten.
Opgelost in andere branches.