Page footer tokens toegevoegd
nl-design-system/lux pull request #249
Opened 2024-09-30 11:59 UTC by AlineNap

- utrecht link-list tokens
- utrecht page-footer tokens

2024-10-01 14:31 UTC, MrSkippy commented
Dit is de build error: 
> proprietary/design-tokens build: 🔧 Building files logius/light/xs.css, logius/light/xs-theme.css
> proprietary/design-tokens build:   Files used: 
> proprietary/design-tokens build: ./**/core/*.json
> proprietary/design-tokens build: ./**/common/**/*.json
> proprietary/design-tokens build: ./**/component/*.json
> proprietary/design-tokens build: ./**/nl/*.json
> proprietary/design-tokens build: ./src/manual/missingTokens.json
> proprietary/design-tokens build: ./src/manual/missingTokens.light.json
> proprietary/design-tokens build: ./**/product/Logius.json
> proprietary/design-tokens build: ./**/mode/light.json
> proprietary/design-tokens build: ./**/viewport/xs.json
> proprietary/design-tokens build: jsonx
> proprietary/design-tokens build: Property Reference Errors:
> proprietary/design-tokens build: **Reference doesn't exist: todo.page-footer.max-block-size.value tries to reference lux.grid.max-block-size, which is not defined**

2024-10-23 09:49 UTC, remypar5 requested changes

2024-10-23 09:49 UTC, remypar5 commented on proprietary/design-tokens/src/imported/$metadata.json
@AlineNap Er zat een merge conflict in dit bestand. Die heb ik opgelost. Daarbij ook meteen de lijst per set(`core`, `nl`, `NLdoc`, etc.) alfabetisch geordend en evt. duplicaten verwijderd. 

Kun je deze nog even goed nakijken of alles nog naar behoren werkt?

2024-10-23 10:30 UTC, AlineNap commented on proprietary/design-tokens/src/imported/$metadata.json
Hij laat goed in, in TS. 

Zaten er duplicaten in? Wat bedoel je daar precies mee?

2024-10-23 10:47 UTC, remypar5 commented on proprietary/design-tokens/src/imported/$metadata.json
Misschien dat de duplicaten door de merge conflicten kwamen. Dat zou kunnen. Ik heb ze in ieder geval verwijderd

2024-10-23 10:48 UTC, remypar5 commented on proprietary/design-tokens/src/imported/$metadata.json
Maar fijn dat het goed gaat on Tokens Studio. Dan sluit ik deze comment

2024-10-23 12:54 UTC, remypar5 approved these changes

2024-10-23 12:54 UTC, merged