chore(components): Utrecht React components toevoegen
nl-design-system/lux pull request #266
Opened 2024-10-01 07:30 UTC by MrSkippy

- Utrecht React components toegevoegd

2024-10-01 09:21 UTC, remypar5 commented on .github/ISSUE_TEMPLATE/new_component_template.md
Deze kun je er wel uit laten. Je gaat straks ook een PR voor dit bestand inschieten

2024-10-01 10:50 UTC, MrSkippy commented on .github/ISSUE_TEMPLATE/new_component_template.md
Prettier made me do it

2024-10-01 10:57 UTC, MrSkippy commented on packages/components-react/src/index.ts
> +export * from '@utrecht/component-library-react';
Ik heb het uit de RHC overgenomen... reden zou kunnen zijn dat als je LUX geïnstalleerd hebt, je niet alsnog Utrecht ernaast hoeft te installeren 🤷‍♂️

2024-10-01 15:10 UTC, remypar5 commented on packages/components-react/src/index.ts
> +export * from '@utrecht/component-library-react';
Dat hoeft sowieso niet. Het is een dep van deze package. Je hoeft ook geen `lodash` te installeren omdat een van de deps daar gebruik van maakt. 

Ik heb liever dat je het weghaalt. Mocht iemand erover struikelen kunnen we er weer naar kijken.

2024-10-02 13:25 UTC, MrSkippy commented on packages/components-react/src/index.ts
> +export * from '@utrecht/component-library-react';
Ook ff in de RHC gevraagd, zij hebben ook geen idee waarom ze het hadden gedaan, ik haal het eruit.

2024-10-02 19:53 UTC, remypar5 requested changes

2024-10-02 19:53 UTC, remypar5 commented on packages/components-react/README.md
> +`pnpm add -D @lux-design-system/components-react --save-dev`
```suggestion
`pnpm add -D @lux-design-system/components-react`
```

2024-10-03 13:33 UTC, remypar5 approved these changes

2024-10-03 13:33 UTC, merged