232 form field component
nl-design-system/lux pull request #299
Opened 2024-10-14 10:03 UTC by VladAfanasev

# Contents

## Checklist

- [X] New features/components and bugfixes are covered by tests
- [X] Changesets are created
- [X] Definition of Done is checked

2024-10-15 12:56 UTC, remypar5 requested changes

2024-10-15 12:56 UTC, remypar5 commented on packages/storybook/src/components-react/form-field-label/FormFieldLabel.mdx
> +Lux Form Field Label is gebaseerd op Utrecht Form Label.
Deze zin mag weg. Het is voor de gebruiker niet van belang welk component er onderwater wordt gebruikt.

Het `CitationDocumentation` component is een ander geval. Daarin geven we aan dat de documentatie van Utrecht afkomt.

2024-10-15 12:56 UTC, remypar5 commented on packages/storybook/src/components-react/form-field-label/FormFieldLabel.mdx
> +## Uitbreidingen in Lux Form Field Label ten opzichte van Utrecht Form Label
```suggestion
## Opmerkingen
```

Zie andere comment over Utrecht componenten die onderwater worden gebruikt.

2024-10-15 12:56 UTC, remypar5 commented on packages/storybook/src/components-react/form-field-label/FormFieldLabel.mdx
> +- De property `type` kan de waarden `'checkbox'` of `'radio'` krijgen om specifieke stijlen toe te passen.
```suggestion
- De property `type` kan de waarden `checkbox` of `radio` krijgen om specifieke stijlen toe te passen.
```

2024-10-16 08:57 UTC, remypar5 commented on packages/components-react/src/heading/Heading.tsx
Zou je deze branch kunnen rebasen op de nieuwe `main`? Of er anderszijds voor zorgen dat de `Heading` changes er niet meer in zitten? Die PR is zojuist gemerged.

2024-10-17 11:09 UTC, VladAfanasev commented on packages/components-react/src/form-field-label/FormFieldLabel.tsx
> +    const classes = [
ik heb er nu dit van gemaakt:
`    const classNames = clsx(
      {
        [FORM_LABEL_CLASSES.base]: true,
        [FORM_LABEL_CLASSES.type]: true,
        [FORM_LABEL_CLASSES.disabled]: disabled,
        [FORM_LABEL_CLASSES.checked]: checked,
      },
      className,
    );`

2024-12-04 08:02 UTC, MrSkippy commented
PR closed, is merged in another PR.

2024-12-04 08:02 UTC, closed without merging