chore(misc) Visual tests en design tokens toegevoegd
nl-design-system/lux pull request #307
Opened 2024-10-18 14:05 UTC by MrSkippy

# Contents

Visual tests en design tokens toegevoegd voor o.a:
- Heading

Code cleanup voor o.a:
- Paragraph

## Checklist

- [ ] New features/components and bugfixes are covered by tests
- ~~[ ] Changesets are created~~ storybook only
- ~~ [ ] Definition of Done is checked ~~

2024-12-19 09:59 UTC, AlineNap requested changes
- De line-height van de pre-heading staat op normal (18px), die mag naar `utrecht.pre-heading.line-height` luisteren.
- Zelfde voor de headings, daar lijkt de line-heigth ook op normal te staan.
- Geen must wel fijn: Gezien we op utrecht geen row-gap toevoegen zou het fijn zijn die token toe te voegen met prefix lux zodat er 4px spacing tussen gezet kan worden. 
-

2024-12-19 13:56 UTC, remypar5 commented
> De line-height van de pre-heading staat op normal (18px), die mag naar `utrecht.pre-heading.line-height` luisteren.

Deze verwijzing is er ook en wordt ook netjes toegepast. Het pad is als volgt:

1. `utrecht.pre-heading.line-height`
2. `lux.line-height.body.default`
3. `viewport.line-height.body.default`
4. `lux.line-height.large-scale.sm`
5. `1.75rem`

2024-12-19 15:37 UTC, AlineNap commented
## reactie op line-hieght

Gek, je hebt gelijk nu staat wel de line-height er goed op. Ook bij de heading-group. 

Ik had screenshots gemaakt ik ben niet gek, :innocent:. Maar er staan ook I'tjes bij wellicht was daar iets mee. 

<img width="1438" alt="line-height pre-heading" src="https://github.com/user-attachments/assets/a1c33049-745f-4e05-a059-64650ad95b2b" />

<img width="1427" alt="line-height heading" src="https://github.com/user-attachments/assets/72a13fee-c61c-45b8-926c-9c511a089ffc" />

2024-12-19 15:43 UTC, AlineNap commented
> Waar wil je dit zien? Deze PR beslaat 3 componenten. 9 als je de aparte heading levels mee rekent

Op de heading group tussen de pre-heading en de heading. Dit is [de aanvraag bij utrecht](https://github.com/nl-design-system/utrecht/issues/2549#issue-2573017552), maar dan dus met lux als prefix.

2024-12-19 15:46 UTC, AlineNap submitted a review, later dismissed

2025-01-02 10:07 UTC, remypar5 approved these changes

2025-01-02 10:08 UTC, merged