feat: added link component
nl-design-system/lux pull request #321
Opened 2024-10-25 15:10 UTC by VladAfanasev

# Contents

Link component toegevoegd op basis van Utrecht Link.

Toevoeging is het icoon met de mogelijkheid om de positie te bepalen zoals bij Button. 

## Checklist

- [X] New features/components and bugfixes are covered by tests
- [X] Changesets are created
- [X] Definition of Done is checked

2024-11-05 12:32 UTC, remypar5 requested changes

2024-11-05 12:32 UTC, remypar5 commented on packages/components-react/src/link/Link.css
> +  display: inline-flex;
```suggestion
  display: inline flex;
```

Deze nieuwe syntax is de new 'n shiny en daarbij de nieuwe standaard. Het is baseline dus we kunnen het veilig gebruiken.

https://developer.mozilla.org/en-US/docs/Web/CSS/display

2024-11-05 12:32 UTC, remypar5 commented on packages/components-react/src/link/Link.tsx
> +  // const content = (
Dit blokje mag weg

2024-11-05 12:32 UTC, remypar5 commented on packages/components-react/src/link/Link.css
> +  order: 0;
Mooi voorbeeld van waar je `order` mag gebruiken. Het maakt niet uit waar het element in de DOM staat, want screenreaders lezen het toch niet op.

2024-11-11 11:30 UTC, MrSkippy commented on packages/components-react/src/link/Link.tsx
Met al deze nieuwe features, weet ik niet of dit nog het Link-component is zoals bij NLDS/Utrecht (daar lijkt deze juist minder uitgebreid te worden...).

Imho: Is dit een "AdvancedLink", deze kan dan blijven bestaan en introduceren we nu al niet een breaking change als we een simplere Link-component willen. @AlineNap @rwittenberns

2024-11-11 11:37 UTC, MrSkippy commented on packages/components-react/src/link/Link.tsx
> +        'aria-label': `${children} (opent in nieuw venster)`,
Kan niet hardcoded erin staan... Is niet te i18n'en.

2024-11-20 08:41 UTC, MrSkippy approved these changes

2024-11-20 08:43 UTC, merged