Components React - Alert
nl-design-system/lux pull request #326
Opened 2024-11-01 10:20 UTC by MMeijerink

# Contents

## Checklist

- [ ] New features/components and bugfixes are covered by tests
- [ ] Changesets are created
- [ ] Definition of Done is checked

2024-11-05 11:44 UTC, remypar5 requested changes

2024-11-05 11:44 UTC, remypar5 commented on packages/storybook/src/react-components/alert/alert.stories.tsx
> +  render: ({ ...args }) => <LuxAlert {...args}>{args['children']}</LuxAlert>,
```suggestion
  render: ({ children, ...args }) => <LuxAlert {...args}>{children}</LuxAlert>,
```

2024-11-05 11:44 UTC, remypar5 commented on packages/storybook/src/react-components/button/button.mdx
> +  url="https://nl-design-system.github.io/utrecht/storybook-css/index.html?path=/docs/css-button--docs"
Oef, goed gevonden man. Dankjewel

2024-11-06 13:43 UTC, MMeijerink commented on packages/components-react/src/alert/Alert.css
> +  /* stylelint-disable-next-line custom-property-pattern */
👍 Ik heb utrecht nu erbij gezet in de linter configuratie

2024-11-06 13:45 UTC, MMeijerink commented
@remypar5 ik heb je comments verwerkt. Thanks voor de feedback en aanvullingen!

2024-11-06 14:50 UTC, remypar5 approved these changes

2024-11-06 14:52 UTC, merged