feat: added RadioButton and RadioGroup components.
nl-design-system/lux pull request #328
Opened 2024-11-04 14:20 UTC by VladAfanasev

# Contents

## Checklist

- [X] New features/components and bugfixes are covered by tests
- [X] Changesets are created
- [X] Definition of Done is checked

2024-11-05 13:29 UTC, remypar5 requested changes

2024-11-05 13:29 UTC, remypar5 commented on packages/components-react/src/radio-group/RadioGroup.tsx
> +        <div className="lux-radio-group__label" id={legendId}>
Er staat mij iets van bij dat @MrSkippy heeft gezegd dat je hier een `<div>` moest gebruiken. Kun je in ieder geval wel de styling van het [`LuxLabel`](proprietary/design-tokens/src/imported/nl/utrecht-form-label.json) toekennen?

2024-11-05 13:29 UTC, remypar5 commented on packages/components-react/src/radio-group/RadioGroup.tsx
> +              onChange={(e) => handleChange(e.target.value)}
Wellicht kunnen we hier ook een `{...optionRestProps}` aan meegeven zodat men ook bvb `data-...` attributes of `className` aan kan toevoegen. Dat bied wat meer vrijheid aan de gebruiker

2024-11-05 13:29 UTC, remypar5 commented on packages/components-react/src/radio-group/RadioGroup.tsx
> +              onChange={(e) => handleChange(e.target.value)}
En de bijkomende tests, natuurlijk

2024-11-05 13:31 UTC, remypar5 submitted a review, later dismissed

2024-11-05 13:31 UTC, remypar5 commented on packages/components-react/src/radio-group/RadioGroup.tsx
> +      <div ref={ref} role="radiogroup" className={groupClassName} aria-required={required} aria-labelledby={legendId}>
Offline besproken is dat we hier toch wel een `<fieldset>` en `<legend>` gaan gebruiken waarbij de `legend` wordt gestijld met de [`lux-form-label`](proprietary/design-tokens/src/imported/nl/utrecht-form-label.json) tokens

2024-11-11 10:22 UTC, MrSkippy commented on packages/components-react/src/radio-button/RadioButton.tsx
Dit component mag het [FormFieldRadioOption](https://nldesignsystem.nl/form-field-radio-option) worden,
De LuxRadioButton is alleen de UtrechtRadioButton, dat is een apart component

2024-11-11 10:27 UTC, MrSkippy commented on packages/components-react/src/radio-group/RadioGroup.tsx
Dit mag het FormFieldRadioGroup worden.

2024-11-11 10:30 UTC, MrSkippy commented on packages/components-react/src/radio-button/RadioButton.tsx
> +        <label className={CLASSNAME.label} htmlFor={radioId}>
Dit mag een FormFieldLabel worden met `radio` property

2024-11-11 10:42 UTC, MrSkippy commented on packages/components-react/src/radio-group/RadioGroup.tsx
> +    const [internalValue, setInternalValue] = useState<string>('');
Vergeet niet `'use client'` bovenin het component te zetten, aangezien je useState gebruikt

2024-11-18 07:46 UTC, MrSkippy approved these changes

2024-11-18 07:49 UTC, MrSkippy approved these changes

2024-11-20 08:50 UTC, MrSkippy approved these changes

2024-11-20 08:53 UTC, merged