Select Component React
nl-design-system/lux pull request #329
Opened 2024-11-06 09:21 UTC by MMeijerink

# Contents

## Checklist

- [ ] New features/components and bugfixes are covered by tests
- [ ] Changesets are created
- [ ] Definition of Done is checked

2024-11-06 10:49 UTC, remypar5 requested changes

2024-11-06 10:49 UTC, remypar5 commented on packages/components-react/src/select/Select.tsx
> +export const LuxSelect = UtrechtSelect;
Dit zijn de allerbeste! Gewoon `import`/`export`

2024-11-06 10:49 UTC, remypar5 commented on packages/storybook/src/react-components/select/select.mdx
> +### Required
Het verbaast mij dat de MD linter hier niet over struikelde. Koppen moeten nl. een witregel voor en na de kop hebben. Ik ga dit fixen

2024-11-06 10:49 UTC, remypar5 commented on packages/components-react/src/index.ts
Ik zal dit merge conflict wel oppakken

2024-11-06 10:49 UTC, remypar5 commented on packages/storybook/src/react-components/select/select.stories.tsx
> +      {selectOptions &&
Deze 2 checks zijn niet nodig, toch? `selectOptions` is hard-coded dus we weten dat deze bestaat en een aantal opties bevat.

2024-11-06 13:17 UTC, remypar5 submitted a review, later dismissed

2024-11-06 13:17 UTC, remypar5 commented on packages/components-react/src/select/Select.tsx
> +export const LuxSelect = UtrechtSelect;
We moeten hier wel nog de `.displayName` bepalen.

2024-11-11 11:21 UTC, MrSkippy submitted a review, later dismissed

2024-11-11 11:24 UTC, MrSkippy commented
Nog even de laatste `main` mergen en `displayName` bij components.

2024-11-26 12:09 UTC, MrSkippy approved these changes

2024-11-26 12:12 UTC, MrSkippy submitted a review, later dismissed

2024-11-27 14:44 UTC, merged