test(components-react): add visual baseline to all formfield components
nl-design-system/lux pull request #347
Opened 2024-12-16 11:18 UTC by MrSkippy

# Contents

Add visual tests baseline to all formfield components

## Checklist

- [x] New features/components and bugfixes are covered by tests
- ~Changesets are created~
- ~Definition of Done is checked~

2024-12-19 12:47 UTC, remypar5 requested changes

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field-description/form-field-description.stories.tsx
> +    <VisualRegressionWrapper className={`lux-theme--logius-light`}>
Hier ook graag een `VisualStates` component introduceren

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field-label/form-field-label.stories.tsx
> +    <VisualRegressionWrapper className={`lux-theme--logius-light`}>
`VisualStates`

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field-radio-group/form-field-radio-group.stories.tsx
> +  <div className="utrecht-document">
`VisualStates`

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field-radio-option/form-field-radio-option.stories.tsx
> +    <VisualRegressionWrapper className={`lux-theme--logius-light`}>
`VisualStates`

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field-select/form-field-select.stories.tsx
> +    <VisualRegressionWrapper className={`lux-theme--logius-light`}>
`VisualStates`

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field-textbox/form-field-textbox.stories.tsx
> +    <VisualRegressionWrapper className={`lux-theme--logius-light`}>
`VisualStates`

2024-12-19 12:47 UTC, remypar5 commented on packages/storybook/src/react-components/form-field/form-field.stories.tsx
> +    <VisualRegressionWrapper className={`lux-theme--logius-light`}>
`VisualStates`

2024-12-19 13:01 UTC, AlineNap reviewed
## Form field label
Top, geen opmerkingen

## Form field description

1. De component tokens voor de kleur van invalid en valid staan op grijs. Hoe kan het dat deze dan toch rood en groen zijn bij de voorbeelden, onderaan in Storybook. In de playground werkt het goed.
2. Zouden wij invalid en valid eruit kunnen halen? 

## Form field error message

1. Wat is de variant distanced? Hebben wij die nodig?

## Textbox

1. Bij invalid zou de border rood moeten
2. Huisnummer veld zou korter mogen, zoals Utrecht dat ook heeft. Er is vanuit Logius nog niet nagedacht hoe al die voorbeelden eruit zouden moeten zien die zijn toegevoegd. Wat is voordeel van deze voorbeelden? Misschien beter om ze eruit te halen?
3. De focus visible voorbeeld heeft geen focus outline.
4. Ik mis voorbeelden van de verschillende states in Storybook

## Select

1. Er mist een icon aan de linkerkant

## Select (documentatie)

1. In de voorbeelden van de states is de value van de select gebruikt om de state aan te duiden, als je een andere state selecteert luister het daar niet naar. Fijner is om met een titel boven de select de state aan te duiden net als utrecht doet: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-select--docs. 
2. In het voorbeeld heeft de hover een dikke border maar als ik over de select heen hover wordt de border niet dik. Heeft dat te maken met ticket utrecht? 
3. Wordt select an option ook doorgegeven in het component? Dan beter om die tekst in het Nederlands te doen. 


## Form field

1. Met de utrecht.form-field.row-gap zou ik spacing verwachten tussen label, description en de error-message. 

## Form field radio option

1. Radiobutton is 24px, zou moeten luisteren naar utrecht.radio-button.size (18px). Wat is jullie voorstel? 
2. Zelfde voor de dot in het midden die zou moeten luisteren naar utrecht.radio-button.icon.size (10px).
3. De radio lijkt niet gecentreerd met de eerste regel van het label. Zie screenshot

## Form field radio group

1. Invalid heeft hier de error message bovenin. Graag 1 lijn trekken bij alle formfields, of boven de input of na de input. 
2. Tussen de radio options hoort lux.radio-group.row-gap(paars) toegepast te zijn dat gaat goed maar deze staat los van de spacing tussen het label, de description en de lux.radio-group zelf. Zie screenshot.

## Losse vragen

1. Wat is het verschil tussen form field en from-field textbox? 

## Form field checkbox

1. Graag spacing tussen de error message en checkbox toevoegen die gelijk staat aan de utrecht.form-field.row-gap
2. Waar komt de with target variant vandaan? Zie dezelfde vraag bij checkbox los.

![image](https://github.com/user-attachments/assets/e7a3b805-001b-4387-9192-7c1af4738435)

<img width="399" alt="centreren radio" src="https://github.com/user-attachments/assets/9cb38daf-cb89-4d4a-a493-fae3bf66be76" />

2025-01-02 14:51 UTC, remypar5 commented on packages/storybook/config/components.ts
whoops. I thought that was stashed

2025-01-02 14:59 UTC, remypar5 approved these changes

2025-01-03 08:57 UTC, remypar5 approved these changes

2025-01-03 08:57 UTC, merged